### ISSUE TITLE
Create a 're-enter password' box on the Sign Up page 

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#101]
To help users be sure what their password is, please create a 're-enter password' box on the Sign Up page – this should indicate when the passwords don't match.

**Comment by NicolasKieffer** [comment]
Render :
![image](https://user-images.githubusercontent.com/16922410/85442965-06f7a600-b591-11ea-92e1-31a5706bc243.png)

**Comment by NicolasKieffer** [comment]
Closed by mistake sorry.
