### ISSUE TITLE
Add New Dataset always has Calorimetry as data type

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#104]
The data type for 'Add New DataSet' should be the most likely type of data for that sentence [Production Version]

**Comment by NicolasKieffer** [comment]
"Calorimetry" is "default value" set when dataseer-ml process do not detect dataset in sentence.

Example :
![image](https://user-images.githubusercontent.com/16922410/87946944-f577c000-caa2-11ea-833d-bcc053a73da7.png)
For this sentence, there is no dataset so the default value will be set.

Note : default data type will be not anymore Calorimetry ("fisrt of list" of datatypes) but "Tabular Data" (datatype with higher "count").

**Comment by timvines19** [comment]
Thanks, that's a good change. Chances are pretty good that it's Tabular data anyway. 

However, it doesn't really make sense that the algorithm is trying to work out whether a sentence added by an author is a data sentence or not –  @kermitt2 could it instead just assume that it is a data sentence and go straight to working out the data type?
