### ISSUE TITLE
User front page

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/dataseer-web#29]
Set-up a user front page to load a paper. 
Currently we have backend version for loading papers (see below). For the user, the difference would be:
- add additional explanatory text (see below, but also keep info about the supported file formats)
- `identify datasets automatically` option always one (so no check box),
- the following "sucess" page does not appear, it goes straight to the main UI for that article.

Some template for the text to be added: 

```
Upload an article

DataSeer is powered by AI, which means it’s always learning and improving.

At the moment, it’s pretty foolish. By uploading your article and telling it about the things it gets right and gets wrong about your datasets, you’re helping DataSeer improve. It’s currently happiest with published articles.

N.B. We define something as its own ‘data type’ if it needs its own sharing instructions. So, ‘Tabular Data’ is one data type, regardless of whether it’s a table of data from physics or from sociology.

You may feel an urge to go to the wiki and add a new data type for your data. It’s vital we keep DataSeer simple and easy to use, so please only add a data type if it’s impossible to fit it under any existing type.

Upload your article:

[Choose files button]

[Upload]
```

**Comment by NicolasKieffer** [comment]
Fixed in : https://github.com/kermitt2/dataseer-web/commit/10dee3f5f1f6580b1bedc4441b31d6e024cec750
