### ISSUE TITLE
Result(s) Filter in All documents window should be case-insensitive

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#32]
Searching for 'androgen' gives no results, whereas searching for 'Androgen' correctly pulls up the article at the top of the list

**Comment by NicolasKieffer** [comment]
Fixed in commit https://github.com/kermitt2/dataseer-web/commit/1b96b64307e7cd79898eff98436ebb96f291df19

_Case insensitive on all 'search' inputs (documents or accounts)_

**Comment by NicolasKieffer** [comment]
Merge in master done https://github.com/kermitt2/dataseer-web/pull/53
