### ISSUE TITLE
Data Accessibility statement on Results page should include datasets with just comments

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#33]
When the author does not provide a DOI and instead writes a comment, these datasets should still be included in the 'Suggested Data Accessibility statement' on the Results page

**Comment by NicolasKieffer** [comment]
Done in commit https://github.com/kermitt2/dataseer-web/commit/febaaba8ca93f5fca23fa8df3664c8d2ac61986f

Updated view :
![image](https://user-images.githubusercontent.com/16922410/75709937-f199fb80-5cc3-11ea-8f2c-15eb1579677c.png)

**Comment by NicolasKieffer** [comment]
Merge in master done https://github.com/kermitt2/dataseer-web/pull/53
