### ISSUE TITLE
reformat dataset results page

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#34]
On the results page it's hard to read the results, particularly for the first 'datasets' section. Could we try reformatting this so the headings are clearer?

e.g. Heading4: DataSets
Heading5 Dataset dataset-1 :
strong" Data Type
etc
Having the extra line between Data Sentence and DataSet name is also a bit confusing.
Simplest solution might be removing this extra line and removing the "strong" from Data Type, Data Sentence etc
![Screen Shot 2020-02-21 at 1 07 19 PM](https://user-images.githubusercontent.com/49563305/75072159-be799000-54ab-11ea-846d-45d0be961982.png)

**Comment by NicolasKieffer** [comment]
Done in commit https://github.com/kermitt2/dataseer-web/commit/0ffa49a6ed3b1fd1c1572139843268d04986f08a

Updated view :
![image](https://user-images.githubusercontent.com/16922410/75708596-67e92e80-5cc1-11ea-9fed-c7ee715c116d.png)
