### ISSUE TITLE
Article upload page for regular users

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#36]
The later sentences should be deleted. Text should read:

DataSeer is powered by AI, which means it’s always learning and improving.
By uploading your article and telling it about the things it gets right and gets wrong about your datasets, you’re helping DataSeer improve.

**Comment by kermitt2** [comment]
commit 93e30662a10fbb2854936106ab557bc5bbc8fd67

I've just replaced AI by Machine Learning... I think "AI" is a bit meaningless and misleading today, and AI as such in general does not always refer to algorithms that are learning and improving.
