### ISSUE TITLE
Data sub-types also appearing in the "Data type" drop down list

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/dataseer-web#37]
For instance data sub-types for chromatography or spectrometry are present in the "Data types" drop-down selection list.

![Screenshot from 2020-03-03 15-06-10](https://user-images.githubusercontent.com/2340795/75783330-b39ee500-5d60-11ea-9dc9-2129fad67894.png)

**Comment by NicolasKieffer** [comment]
Fixed in https://github.com/kermitt2/dataseer-web/pull/54

**Comment by kermitt2** [comment]
Just reopening some issues, so that the initial poster closes the issue after test, it's better practice than the developer closing himself the issue imho.

**Comment by NicolasKieffer** [comment]
_Additional fix in https://github.com/kermitt2/dataseer-web/pull/58_

**Comment by timvines19** [comment]
Looks like the sub types are back in the drop down menu
![Screen Shot 2020-03-09 at 10 07 31 AM](https://user-images.githubusercontent.com/49563305/76238923-df511d80-61ed-11ea-8c2f-faf90f60bf64.png)

**Comment by kermitt2** [comment]
My fault, I redeployed the wrong branch for online web app! 
I have redeployed the right master version, you should see the change now Tim.
