### ISSUE TITLE
is the 'All Documents' list complete?

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#47]
Jonno Threlfall from F1000 emailed me about an article he ran through DataSeer (titled "Effect of public-private interface agency in Patna and Mumbai, India: Does it alter durations 1 and delays in care seeking for drug sensitive pulmonary tuberculosis")

But I can't find in the list of 'All documents'. The molecular Connections people have presumably also uploaded a lot of documents but there's only 12 there.

**Comment by NicolasKieffer** [comment]
'All documents' mean 'documents of all users'.
_Unlike 'My document' that will only show yours (uploaded or modified by you)_

But there is always only 20 documents shown by default.

Get more results by using **limit** :
![image](https://user-images.githubusercontent.com/16922410/76011118-56e42b80-5f14-11ea-9a57-7339dd109469.png)

**Comment by timvines19** [comment]
Does the Result(s) search bar only look within the displayed documents? That's a bit counterintuitive, it would be better if it searched all of them
