### ISSUE TITLE
Enable selection of sentences in figure captions

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#59]
related to #40 

A temporary workaround would be to allow users to select sentences from figure captions

**Comment by kermitt2** [comment]
commit d65e2cd7776a7399b50924628ba91138dcd0c352 in dataseer-ml should allow that in dataseer-web

**Comment by kermitt2** [comment]
@timvines19 I've redeployed dataseer-ml, so you can test it I think
