### ISSUE TITLE
UI not pulling information from Wiki

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#61]
The UI is still showing the temporary text for e.g. Tabular Data, and not the text on the wiki

![Screen Shot 2020-03-09 at 2 51 34 PM](https://user-images.githubusercontent.com/49563305/76260719-afb60b80-6215-11ea-848d-0e060d188602.png)

![Screen Shot 2020-03-09 at 2 51 55 PM](https://user-images.githubusercontent.com/49563305/76260717-ae84de80-6215-11ea-90eb-7199d1057663.png)

**Comment by NicolasKieffer** [comment]
Bug caused by difference between property names.

Keys used by dataseer-ml
![image](https://user-images.githubusercontent.com/16922410/76653044-334e6000-6568-11ea-91bf-e4a447a436a8.png)

Key used by dataseer-web (& mongoDB) :
![image](https://user-images.githubusercontent.com/16922410/76653233-8e805280-6568-11ea-9875-6eb91d386ba2.png)

Easiest way (for me) would be to modify properties names of dataseer-ml result @kermitt2 
Else, i can fix in dataseer-ml but re-upload of all documents in MongoDB will be necessary

**Comment by kermitt2** [comment]
Could you just map the property names from the json datatype description file to the dataseer-web format? Not suure but aren't you doing it anyway when calling initially `service/jsonDataTypes` in dataseer-ml?

**Comment by NicolasKieffer** [comment]
Yes, i could do that.

**Comment by timvines19** [comment]
Could we please try to fix this issue this week? There's quite a few other things that are waiting for it (e.g. making a user video), and it's also hard to do a good product demonstration without the info from the wiki appearing in the UI

**Comment by NicolasKieffer** [comment]
I will push fix tonight

**Comment by NicolasKieffer** [comment]
Done in https://github.com/kermitt2/dataseer-web/pull/73

**Comment by NicolasKieffer** [comment]
dataseer-web need to be restarted for this update (@kermitt2)

**Comment by kermitt2** [comment]
@timvines19 you can test the fix on the dev instance -> 
http://dataseer-dev.science-miner.com

**Comment by timvines19** [comment]
This seems to be working now, with the caveat that the way links get displayed in the wiki doesn't lead to them being links on the UI
![Screen Shot 2020-03-23 at 7 54 02 AM](https://user-images.githubusercontent.com/49563305/77329772-b051a600-6cdb-11ea-873a-7f607324d647.png)

**Comment by NicolasKieffer** [comment]
_Note : Description, Best data format for sharing & Most suitable Repositories values from MongoDB are no more used to display data in dataseer-web. Only data from wiki are used_

**Comment by timvines19** [comment]
Looks like it's working well on the dev platform. Please roll it out to the production version
