### ISSUE TITLE
DNS mapping for DataSeer.io to the ML (rather than science miner)

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#65]

**Comment by timvines19** [comment]
OK - dataseer.io is hosted on Digital Ocean (https://cloud.digitalocean.com/login)

username tim.h.vines@gmail.com

pwd WkZHLtjj8H!K5*z

It'll likely want a verification code because you're logging in from a new computer but I'll pass that along when it gets emailed to me

The DNS is: https://www.namecheap.com/

username: timvines
pwd: s6sX6P2HcyW54F7

**Comment by kermitt2** [comment]
see #70
