### ISSUE TITLE
change hosting address to dataseer.io/app

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#70]
or something like that e.g. app.dataseer.io

**Comment by timvines19** [comment]
website will actually be moving to dataseer.ai instead, so maybe app.dataseer.ai?

**Comment by kermitt2** [comment]
It might be rather `dataseer.ai/app` for obscure technical reason :) but I will try both

**Comment by kermitt2** [comment]
So updated via `app.dataseer.ai` 
dev server remains as dataseer-dev.science-miner.com because it's just for our tests.
