### ISSUE TITLE
enable curators to 'Finish' document as well

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#71]
Currently only annotators and standard_users can reach the Finish page

**Comment by NicolasKieffer** [comment]
Curator role still disable "Security of Form" (when 'Finish' or 'Validate' button is clicked)
_Modal will never be shown & data will be saved_

**Comment by timvines19** [comment]
Could you clarify what you mean by modal?

**Comment by NicolasKieffer** [comment]
This element : 
![image](https://user-images.githubusercontent.com/16922410/77367234-02391100-6d5a-11ea-9b53-430a548a40bc.png)

**Comment by timvines19** [comment]
ok, that's fine
