### ISSUE TITLE
Dataset form blanks

### ISSUE THREAD

**Issue by NicolasKieffer** [kermitt2/dataseer-web#75]
In case **subtype** has no information provided for "Description", "Best data format for sharing" or "Most suitable Repositories", app do not display anything.

Does app must diplay datatype's information instead?

Like :

No data in this subtype for "Best data format for sharing" and "Most suitable Repositories"
![image](https://user-images.githubusercontent.com/16922410/77352290-41a63400-6d3f-11ea-8a96-a32b48de7044.png)

But dataype has "Best data format for sharing" and "Most suitable Repositories"
![image](https://user-images.githubusercontent.com/16922410/77352339-57b3f480-6d3f-11ea-8471-1c68e6bbcdb5.png)

"Merged" informations of datatype & subtype :
![image](https://user-images.githubusercontent.com/16922410/77352434-787c4a00-6d3f-11ea-8849-66cd19d07506.png)

**Comment by timvines19** [comment]
In the long run I think it would be best for the subtype to reflect the contents of the wiki. If the info for the subtype is blank then I should go fill it in.

However, if this is relatively easy to implement then please go ahead...
