### ISSUE TITLE
enable 'forgot password' function on sign in page, plus 're-enter password'

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#90]
Also, would be great for curators to be able to change people's passwords

**Comment by NicolasKieffer** [comment]
**enable 'forgot password' function on sign in page**

I do not understand, **_Forgot Password_** function is already accessible via url in "navbar"
(top right, after "Sign in")
![image](https://user-images.githubusercontent.com/16922410/85022487-a96bef80-b173-11ea-92b8-cce2f7f47c1e.png)
Should i add _Forgot Password_ form "after" _Sign in_ form on same page?
Or should i add link after _Sign in to Dataseer_ button?

Note : When you're logged in, you can set new password with _**Settings**_
![image](https://user-images.githubusercontent.com/16922410/85023776-79bde700-b175-11ea-8dd5-444154523c7d.png)

**plus 're-enter password'**

Is it not rather on _**Sign-up**_ page than on _**Sign-in**_ page?

**Also, would be great for curators to be able to change people's passwords**

I'm not sure that Curators knows users passwords would be a good idea. Anyone who want to update its password can do it (logged : settings, or not : forgot password). Credentials will be send to its email address then.

**Comment by timvines19** [comment]
Ah, OK. I'm used to seeing the 'forgot password' link under the Sign In button, as that's where it is on most websites. So, please do add a second 'forgot password' link under the Sign in to DataSeer button

**Comment by NicolasKieffer** [comment]
Render :
![image](https://user-images.githubusercontent.com/16922410/85403015-f9282d80-b55c-11ea-86c1-a4df885657cd.png)
![image](https://user-images.githubusercontent.com/16922410/85403036-004f3b80-b55d-11ea-851c-72104ef05d53.png)

**Comment by timvines19** [comment]
Thanks, looks good.

Will move the 'Please also create a 're-enter password' box on the Sign Up page so that people can be sure what their password is.' to a separate issue
